
name: Build Portable EXE (Offline)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build portable
        run: npm run portable

      - name: Upload portable exe
        uses: actions/upload-artifact@v4
        with:
          name: portable-exe
          path: "dist/Maxwell-Training-Dashboard-Portable-*.exe"
